server:
  port: 8080

spring:
  datasource:
    name: student
    url: jdbc:mysql://localhost:3306/student?useSSL=false
    username: root
    password: root
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
    #热部署--静态资源立即生效
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: LEGACYHTML5
    check-template-location: true
  #热部署生效
devtools:
  restart:
  enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.project.student.domain