server:
  port: 8080

spring:
  datasource:
    name: student
    url: jdbc:mysql://49.232.29.113:3306/student?useSSL=false
    username: root
    password: 123456
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
    #热部署--静态资源立即生效
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: LEGACYHTML5
    check-template-location: true
  #热部署生效
devtools:
  restart:
  enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.project.student.domain
  global-config:
    db-config:
      logic-delete-value: Y # 逻辑已删除值(默认为 Y)
      logic-not-delete-value: N # 逻辑未删除值(默认为 N)
logging:
  level:
    com.project.student: debug
    com.baomidou: info
    org.springframework: info
    org.thymeleaf: info
  file:
    path: ./src/main/resources/log